services:
  bde-tv:
    container_name: bde-tv
    image: ghcr.io/zeluck-github/bdetv:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - /opt/apps/bde-tv/tmp:/app/tmp
      - /opt/apps/bde-tv/storage/uploads:/app/storage/uploads
    restart: always